name: build-and-push

on:
  workflow_run:
    workflows:
      - lint
    types:
      - completed

jobs:
  build-and-push:
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - run: echo "commit_hash=$(git rev-parse --short main)" >> $GITHUB_OUTPUT
        id: commit_hash

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - run: |
          docker build -t ghcr.io/${{ github.repository }}:${{ steps.commit_hash.outputs.commit_hash }} -t ghcr.io/${{ github.repository }}:latest .

      - run: |
          docker push ghcr.io/${{ github.repository }}:${{ steps.commit_hash.outputs.commit_hash }}
          docker push ghcr.io/${{ github.repository }}:latest
